---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
- name: titanium

params:
  aws-access-key-id: ((aws-access-key-id))
  aws-access-key-id: ((aws-secret-access-key))

run:
  path: printenv
