---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
- name: titanium

params:
  AWS_KEY: ((aws-access-key-id))
  AWS_SECRET: ((aws-secret-access-key))

run:
  path: ./titanium/build.sh
