---
platform: linux

image_resource:
  type: docker-image
  source: {repository: adoptopenjdk/openjdk8-openj9, tag: latest}

inputs:
- name: titanium

params:
  AWS_ACCESS_KEY_ID: "((aws-access-key-id))"
  AWS_SECRET_ACCESS_KEY: "((aws-secret-access-key))"

run:
  path: sleep
  args:
    - 9999999
  dir: titanium
