---
platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: openjdk-8}

inputs:
- name: titanium

run:
  path: gradle
  args:
    - "--no-daemon"
    - "build"
  dir: titanium
