---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
  - name: config

params:
  AWS_KEY: ((concourse.aws-access-key-id))
  AWS_SECRET: ((concourse.aws-secret-access-key))

run:
  path: titanium/ci/configure.sh
