resources:
- name: titanium
  type: git
  source:
    uri: https://bitbucket.org/hrznstudio/titanium.git

groups:
- name: build
  jobs:
  - Build

jobs:
- name: Build
  public: true
  plan:
  - get: titanium
    trigger: true
  - task: build
    file: titanium/ci/build.yml
