resources:
- name: titanium
  type: git
  source:
    uri: https://bitbucket.org/hrznstudio/titanium.git
- name: version
  type: semver
  source:
    driver: s3
    bucket: cdn.hrzn.studio
    key: semvers/titanium
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))

groups:
- name: build
  jobs:
  - Build

jobs:
- name: Build
  public: true
  plan:
  - get: titanium
    trigger: true
  - put: version
    params: {bump: patch}
  - task: build
    file: titanium/ci/build.yml
